basePath: /
host: localhost:8080
info:
  contact: {}
  version: "1.0"
paths:
  /isAlive:
    get:
      responses:
        "200":
          description: OK
      summary: checking server is alive
swagger: "2.0"
